---
# tasks file for dnsServer
- name: Test if selinux is enabled
  command: /usr/sbin/selinuxenabled
  ignore_errors: yes
  register: selinux_status

- name: Get service facts
    service_facts:

- name: Check the status of both selinux and fiewalld
  debug:
    var: selinux_status.rc
  when: ansible_facts.services.firewalld.state == "Active" and selinux_status.rc == 0
  notify: disable selinux and firewalld

- name: Install the needed software packages
  ansible.builtin.package:
      name: "{{ item }}"
      state: present
  loop:
      - bind
      - bind-utils

- name: Copy named.conf
  template:
    src: named.conf.j2
    dest: /etc/named.conf

- name: Copy named.zone file
  template:
    src: named.zone.j2
    dest: /etc/{{ DOMAIN_NAME }}.zone
  notify:
    - restart named

- name: Copy forward zone file
  template:
    src: forward.zone.j2
    dest: /var/named/forward.zone

- name: Copy reverse zone file
  template:
    src: reverse.zone.j2
    dest: /var/named/reverse.zone
  notify: 
    - check named.conf syntax
    - check forward zone file syntax
    - check reverse zone file syntax
    - restart named
