---
# tasks file for OpenHPC_server
- name: Install the epel repository
  ansible.builtin.package:
    name: epel-release
    state: present

- name: Enable the PowerTools repository
  shell: "crb enable"

- name: Setup the ohpc repo access
  ansible.builtin.package:
    name: "{{ OPENHPC_URL }}"
    state: present
    disable_gpg_check: "{{ disable_ansible.builtin.package_gpg_check | d(omit)  }}"

- name: Install the basic packages needed for the ohpc server
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  loop:
    - "{{ OPENHPC_BASIC_PACKAGES }}"

- name: Start the sms host setup
  include_tasks: sms_configurations.yaml
