- name: Create the basic image folder setup
  shell: wwmkchroot -v rocky-8 "{{ COMPUTE_NODE_CHROOT_PATH }}"

- name: copy files from sms into node image
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  loop:
      - { src: /etc/resolv.conf, dest: "{{ COMPUTE_NODE_CHROOT_PATH  }}/etc/" }
      - { src: /etc/passwd, dest: "{{ COMPUTE_NODE_CHROOT_PATH  }}/etc/" }
      - { src: /etc/group, dest: "{{ COMPUTE_NODE_CHROOT_PATH  }}/etc/" }
      - { src: /etc/yum.repos.d/OpenHPC.repo, dest: "{{ COMPUTE_NODE_CHROOT_PATH  }}/etc/yum.repos.d/" }

- name: Install needed packages inside base image
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
    installroot: "{{ COMPUTE_NODE_CHROOT_PATH }}"
    disable_gpg_check: "{{ disable_yum_gpg_check | d(omit)   }}"
  loop: "{{ BASE_IMAGE_INITIAL_PACKAGES }}"

- name: Install the kernel and lmod rpms inside the image
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  loop:
    - "kernel-{{ kernel_version.stdout  }}"
    - lmod-ohpc

- name: Configure the slurmd daemon inside the image
  blockinfile:
    path: "{{ COMPUTE_NODE_CHROOT_PATH  }}/etc/sysconfig/slurmd"
    block: |
      "SLURMD_OPTIONS='--conf-server {{ OHPC_MASTER_HOSTNAME }}'"
    create: true

- name: Configure the chronyd daemon inside the image
  lineinfile:
    state: present
    insertafter: EOF
    dest: "{{ COMPUTE_NODE_CHROOT_PATH }}/etc/chrony.conf"
    line: "server {{ OHPC_IP_ADDRESS }} iburst prefer"

- name: Enable slurmd and munge inside the image
  shell: "chroot {{ COMPUTE_NODE_CHROOT_PATH }} systemctl enable --now slurmd munge"
  ignore_errors: True
